name: Lint
on:
  push:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golang-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - name: Install templ runtime
        run: go get github.com/a-h/templ/runtime
      - name: Build templ
        run: templ generate .
      - name: golang-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
